name: Publish
on:
  push:
    branches:
      - main

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Check format
        run: deno fmt ./src --check

      - name: Check lint
        run: deno lint ./src

      - uses: paambaati/codeclimate-action@v9.0.0
        env:
          CC_TEST_REPORTER_ID: 6820fc642378c2fa9a414365561d0fadf2e15614bfbb8cedb2b2432644826651
        with:
          coverageCommand: deno run ci
          coverageLocations: |
            ${{github.workspace}}/*.lcov:lcov

  publish:
    runs-on: ubuntu-latest
    needs: [checks]

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Publish package
        run: deno publish
